### ISSUE TITLE
Cannot compile without `parallel` feature enabled

### ISSUE THREAD

**Issue by coffeebeats** [ten3roberts/hecs-schedule#2]
While investigating #1, I tried to disable the `parallel` feature since I don't need parallel system execution (I use this library indirectly via `hecs-hierarchy`). This results in the following error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `rayon`
 --> src/traits.rs:4:5
  |
4 | use rayon::iter::{ParallelBridge, ParallelIterator};
  |     ^^^^^ use of undeclared crate or module `rayon`

error[E0599]: no method named `par_bridge` found for struct `BatchedIter` in the current scope
  --> src/traits.rs:55:14
   |
55 |             .par_bridge()
   |              ^^^^^^^^^^ method not found in `BatchedIter<'_, Q>`

error[E0599]: no method named `par_bridge` found for struct `BatchedIter` in the current scope
  --> src/traits.rs:65:14
   |
65 |             .par_bridge()
   |              ^^^^^^^^^^ method not found in `BatchedIter<'_, Q>`
   ```

I think this can be resolved by adding `#[cfg(feature="parallel")]` attributes to the relevant traits in `src/traits.rs` and the `rayon` imports. I'm happy to open a PR if that would be helpful/is the solution you'd prefer.

**Comment by ten3roberts** [comment]
The issue has now been fixed, and both hecs-schedule and hecs-hierarchy have been updated to the latest version of hecs.

Additionally, hecs-hierarchy no longer enables the default pararell feature in the dependency to hecs-schedule
