### ISSUE TITLE
IncompatibleSubworld panic

### ISSUE THREAD

**Issue by konceptosociala** [ten3roberts/hecs-schedule#5]
I have such implementation of `App`

```rust

pub struct Despero { 
         world: World, 
         schedule: ScheduleBuilder, 
         renderer: Renderer, 
 } 
  
 impl Despero {         
         pub fn init(window_builder: WindowBuilder) -> Despero { 
                 let renderer = Renderer::init(window_builder).expect("Cannot create renderer"); 
                 Despero { 
                         world: World::new(), 
                         schedule: Schedule::builder(), 
                         renderer, 
                 } 
         } 
          
         pub fn add_system<Args, Ret, S>(mut self, system: S) -> Self  
         where 
         S: 'static + System<Args, Ret> + Send, 
         { 
                 self.schedule.add_system(system); 
                 self 
         } 
          
         pub fn run(mut self) { 
                 self. 
                         schedule 
                                 .add_system(eventloop_system) 
                                 .build() 
                                 .execute((&mut self.world, &mut self.renderer)) 
                                 .expect("Cannot execute schedule"); 
         } 
 }

```
where `eventloop_system`(winit) is like

```rust

pub(crate) fn eventloop_system( 
         renderer: Write<Renderer>, 
         mut camera_world: SubWorld<(&mut Camera, &Transform)>, 
 ){ 
         // Reassign `Renderer` and `SubWorld` (to get them in EventLoop)
         let mut renderer = renderer; 
         let camera_world = &mut camera_world; 
          
         // Unwrap `EventLoop` (to get it from struct `Renderer`)
         let mut el = None; 
         std::mem::swap(&mut el, &mut renderer.eventloop); 
         let mut eventloop = el.unwrap(); 
         
         // Run eventloop
         eventloop.run_return(move |event, _, controlflow| match event {
         ...
             for (_, camera) in &mut camera_world.query::<&mut Camera>(){ 
                 if camera.is_active { 
                     camera.turn_right(0.05); 
                 } 
             }
         ...
         });
}
```
But it panics while querying with error like `Invalid SubWorld`, even though Camera instance is created in a system before, although I wish it didn't matter. What am I doing wrong? 

I am new in game engine craft, but I considered using EventLoop as a system a good ide, so it may be issue.

Also how to make a system cyclical without having `loop` inside? Because it somehow freezes EventLoop

Thank you a lot for what you are doing and thanks in advance for the reply

**Comment by ten3roberts** [comment]
How does the panic message read?

And no, it is usually not a good idea to put the event loop as a system, as an event loop runs forever.

Rather, put the call to `Schedule::exexute` inside each iteration of the event loop in `MainEventsCleared`

**Comment by konceptosociala** [comment]
Sorry, I've forgotten some `mut`s in SubWorld declaration 

> Rather, put the call to `Schedule::exexute` inside each iteration of the event loop in `MainEventsCleared`

Oh, I thought, that it's updated like every frame, but not after finishing of system execution, so the system is executed some times simultaneously. If it is relevant, so it changes everything! Is there a difference between putting  `Schedule::exexute` in `MainEventsCleared` and `RedrawRequested`? Thx a lot

**Comment by ten3roberts** [comment]
Since it seems you are making a game, you want the systems to run for each frame, so `MainEventsCleared` is the way to go

https://docs.rs/winit/latest/winit/event/enum.Event.html#variant.MainEventsCleared

So is the panic fixed, or does it still happen.

What the `eventloop.run` does is highjack the current main thread, and use the system specific way to wait for window events, and then call the provided function to handle them. This is similar to the glfw `while(true) { glfwPollEvents(); // Gameplay code for each frame }`

Furthemore, I am developing another ECS called flax which has builtin support for scheduling and multithreaded dispatching, as well as many other things. It is quite similar to hecs. It may be worth looking at it and see it you find it easier to use. :)

https://github.com/ten3roberts/flax

**Comment by konceptosociala** [comment]
Sorry for not responding, I've been solving some other issues, which happened with the engine 😁, but everything about hecs schedule is working. Thx for you work
