### ISSUE TITLE
Setting system parameters from outside / SPMC implementation

### ISSUE THREAD

**Issue by konceptosociala** [ten3roberts/hecs-schedule#6]
Hi! I am using [bus crate](https://crates.io/crates/bus/) to make event handling in hecs_schedule's systems. It implements spmc paradigm, so one Bus (producer) pushes an event and many BusReaders (consumers) read this event. It look like this (simplified):
```rust
pub struct EventWriter<E: Clone + Sync> {
	writer: Bus<E>,
}

impl<E: Clone + Sync> EventWriter<E> {
	pub(crate) fn new() -> Self {
		Self { writer: Bus::new(100) }
	}
	
	pub fn send(&mut self, event: E) -> Result<(), EventError<E>> {
		match self.writer.try_broadcast(event) {
			Ok(()) => Ok(()),
			Err(ev) => Err(EventError::Send(ev))
		}
	}
}
```
```rust
pub struct EventReader<E: Clone + Sync> {
	reader: BusReader<E>,
}

impl<E: Clone + Sync> EventReader<E> {
	pub(crate) fn new(event_writer: &mut EventWriter<E>) -> Self {
		Self { 
			reader: event_writer.writer.add_rx(),
		}
	}
	
	pub fn read(&mut self) -> Result<E, EventError<E>> {
		match self.reader.try_recv() {
			Ok(ev) => Ok(ev),
			Err(err) => Err(EventError::Read(err))
		}
	}
}
```
Since each system must have access to unique Reader, so putting one `EventReader` struct to the schedule is not appropriate, but as there is defined amount of systems while schedule.execute(), we can (maybe) check, on system adding, if it has argument like EventReader, and set it to custom value. But I can't figure out, how can it be implemented. Sorry if this is of-topic, but as the crate developer you could help me

**Comment by ten3roberts** [comment]
What I've done in situations like these, what could be called `system local` data, I make the system a closure and move the event reader into it. To split things up, you can make each system a function which takes an event writer, constructs a reader, and returns a closure system which captures it.

**Comment by konceptosociala** [comment]
> What I've done in situations like these, what could be called `system local` data, I make the system a closure and move the event reader into it. To split things up, you can make each system a function which takes an event writer, constructs a reader, and returns a closure system which captures it.

Could you give a little example, please?

**Comment by ten3roberts** [comment]
```rust

let mut writer = EventWriter::new();

let mut reader = EventReader::new(&mut writer);
let system = move |world: SubWorld<(&Position)>| {
    while let Ok(event) = reader.read() {
        // Do something with `world`
    }
};

let mut reader = EventReader::new(&mut writer);

let system_2 = move || {
    while let Ok(event) = reader.read() {
        eprintln!("Got: {event:?}");
    }
};

```

The two reader will now be captured/moved into the system, and the normal rust ownership rules ensure each have their own reader, and can access it like normal, even in a multithreaded environment since they are owned.
